// This file is auto-generated by @hey-api/openapi-ts

export const AboutCardCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        title: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Title'
        },
        summary: {
            type: 'string',
            maxLength: 1600,
            minLength: 1,
            title: 'Summary'
        },
        media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Id'
        },
        image_alt: {
            type: 'string',
            maxLength: 240,
            title: 'Image Alt',
            default: ''
        },
        layout: {
            type: 'string',
            enum: ['tall', 'wide', 'small'],
            title: 'Layout',
            default: 'small'
        },
        tone: {
            type: 'string',
            enum: ['navy', 'white', 'blue', 'orange'],
            title: 'Tone',
            default: 'white'
        },
        image_fit: {
            type: 'string',
            enum: ['contain', 'cover'],
            title: 'Image Fit',
            default: 'contain'
        },
        image_ratio: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['portrait', 'landscape']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Ratio'
        }
    },
    type: 'object',
    required: ['title', 'summary'],
    title: 'AboutCardCreate',
    description: 'Create one About bento card.'
} as const;

export const AboutCardReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Id'
        },
        image_alt: {
            type: 'string',
            title: 'Image Alt'
        },
        layout: {
            type: 'string',
            title: 'Layout'
        },
        tone: {
            type: 'string',
            title: 'Tone'
        },
        image_fit: {
            type: 'string',
            title: 'Image Fit'
        },
        image_ratio: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Ratio'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'title', 'summary', 'media_id', 'image_alt', 'layout', 'tone', 'image_fit', 'image_ratio'],
    title: 'AboutCardRead',
    description: 'About-card response.'
} as const;

export const AboutCardUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1600,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Id'
        },
        image_alt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 240
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Alt'
        },
        layout: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['tall', 'wide', 'small']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Layout'
        },
        tone: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['navy', 'white', 'blue', 'orange']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tone'
        },
        image_fit: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['contain', 'cover']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Fit'
        },
        image_ratio: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['portrait', 'landscape']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Ratio'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'AboutCardUpdate',
    description: 'Update one About bento card.'
} as const;

export const AdminUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Role Names'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'AdminUserCreate',
    description: 'Payload for creating a user from the admin interface.'
} as const;

export const AdminUserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        role_names: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Names'
        }
    },
    type: 'object',
    title: 'AdminUserUpdate',
    description: 'Payload for admin-managed user updates.'
} as const;

export const Body_upload_media_api_v1_admin_portfolio_media_postSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        },
        alt_text: {
            type: 'string',
            maxLength: 300,
            title: 'Alt Text',
            default: ''
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_media_api_v1_admin_portfolio_media_post'
} as const;

export const CollectionOrderUpdateSchema = {
    properties: {
        ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Ids'
        }
    },
    type: 'object',
    required: ['ids'],
    title: 'CollectionOrderUpdate',
    description: 'Atomic ordered-ID replacement for one collection.'
} as const;

export const ContactAcceptedSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'accepted',
            title: 'Status',
            default: 'accepted'
        }
    },
    type: 'object',
    title: 'ContactAccepted',
    description: 'Non-sensitive public acknowledgement for a stored enquiry.'
} as const;

export const ContactCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 120,
            minLength: 2,
            title: 'Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        subject: {
            type: 'string',
            maxLength: 180,
            minLength: 2,
            title: 'Subject'
        },
        message: {
            type: 'string',
            maxLength: 5000,
            minLength: 10,
            title: 'Message'
        },
        company: {
            type: 'string',
            maxLength: 0,
            title: 'Company',
            default: ''
        }
    },
    type: 'object',
    required: ['name', 'email', 'subject', 'message'],
    title: 'ContactCreate',
    description: 'Public contact enquiry including an invisible bot trap.'
} as const;

export const ContactSubmissionReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        subject: {
            type: 'string',
            title: 'Subject'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        inbox_state: {
            type: 'string',
            title: 'Inbox State'
        },
        delivery_state: {
            type: 'string',
            title: 'Delivery State'
        },
        delivery_attempts: {
            type: 'integer',
            title: 'Delivery Attempts'
        },
        last_delivery_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Delivery At'
        },
        delivered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivered At'
        },
        delivery_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivery Error'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'email', 'subject', 'message', 'inbox_state', 'delivery_state', 'delivery_attempts', 'last_delivery_at', 'delivered_at', 'delivery_error', 'is_archived', 'created_at', 'updated_at'],
    title: 'ContactSubmissionRead',
    description: 'Contact inbox response.'
} as const;

export const ContactSubmissionUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        inbox_state: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['new', 'read', 'replied', 'spam', 'archived']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Inbox State'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'ContactSubmissionUpdate',
    description: 'Update inbox state or archive status.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HeroExpertiseCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        label: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Label'
        },
        icon_key: {
            type: 'string',
            maxLength: 40,
            minLength: 1,
            title: 'Icon Key'
        }
    },
    type: 'object',
    required: ['label', 'icon_key'],
    title: 'HeroExpertiseCreate',
    description: 'Create one hero expertise entry.'
} as const;

export const HeroExpertiseReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        icon_key: {
            type: 'string',
            title: 'Icon Key'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'label', 'icon_key'],
    title: 'HeroExpertiseRead',
    description: 'Hero expertise response.'
} as const;

export const HeroExpertiseUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        icon_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Key'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'HeroExpertiseUpdate',
    description: 'Update one hero expertise entry.'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate',
    description: 'Payload for creating an item.'
} as const;

export const ItemListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemList',
    description: 'Paginated item list response.'
} as const;

export const ItemReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['id', 'title', 'owner_id'],
    title: 'ItemRead',
    description: 'Item data returned by item endpoints.'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate',
    description: 'Payload for updating an item.'
} as const;

export const LoginRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'LoginRequest',
    description: 'Email and password login payload.'
} as const;

export const MediaAssetReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        size_bytes: {
            type: 'integer',
            title: 'Size Bytes'
        },
        width: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Width'
        },
        height: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        },
        checksum: {
            type: 'string',
            title: 'Checksum'
        },
        alt_text: {
            type: 'string',
            title: 'Alt Text'
        },
        storage_kind: {
            type: 'string',
            title: 'Storage Kind'
        },
        static_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Static Path'
        },
        local_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Local Path'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    required: ['id', 'filename', 'mime_type', 'size_bytes', 'width', 'height', 'checksum', 'alt_text', 'storage_kind', 'static_path', 'local_path', 'is_archived', 'created_at', 'updated_at'],
    title: 'MediaAssetRead',
    description: 'Media metadata without binary bytes.'
} as const;

export const MediaAssetUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        filename: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Filename'
        },
        alt_text: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 300
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alt Text'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'MediaAssetUpdate',
    description: 'Editable media metadata.'
} as const;

export const PasswordChangeSchema = {
    properties: {
        current_password: {
            type: 'string',
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'PasswordChange',
    description: "Payload for changing the current user's password."
} as const;

export const PasswordRecoveryRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'PasswordRecoveryRequest',
    description: 'Payload for requesting a password recovery email.'
} as const;

export const PasswordResetRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'PasswordResetRequest',
    description: 'Payload for completing password reset with a token.'
} as const;

export const PermissionReadSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['code', 'description'],
    title: 'PermissionRead',
    description: 'Permission data exposed to the frontend.'
} as const;

export const PortfolioContentResponseSchema = {
    properties: {
        publication: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PortfolioPublicationRead'
                },
                {
                    type: 'null'
                }
            ]
        },
        content: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        source: {
            type: 'string',
            enum: ['published', 'draft', 'none'],
            title: 'Source'
        }
    },
    type: 'object',
    required: ['source'],
    title: 'PortfolioContentResponse',
    description: 'Published or preview aggregate response.'
} as const;

export const PortfolioPostCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        slug: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$',
            title: 'Slug'
        },
        title: {
            type: 'string',
            maxLength: 200,
            minLength: 1,
            title: 'Title'
        },
        excerpt: {
            type: 'string',
            maxLength: 1200,
            minLength: 1,
            title: 'Excerpt'
        },
        body_markdown: {
            type: 'string',
            maxLength: 200000,
            title: 'Body Markdown',
            default: ''
        },
        cover_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Media Id'
        },
        published_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published On'
        },
        seo_title: {
            type: 'string',
            maxLength: 160,
            title: 'Seo Title',
            default: ''
        },
        seo_description: {
            type: 'string',
            maxLength: 320,
            title: 'Seo Description',
            default: ''
        }
    },
    type: 'object',
    required: ['category_id', 'slug', 'title', 'excerpt'],
    title: 'PortfolioPostCreate',
    description: 'Create one Markdown post.'
} as const;

export const PortfolioPostReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        excerpt: {
            type: 'string',
            title: 'Excerpt'
        },
        body_markdown: {
            type: 'string',
            title: 'Body Markdown'
        },
        cover_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Media Id'
        },
        published_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published On'
        },
        seo_title: {
            type: 'string',
            title: 'Seo Title'
        },
        seo_description: {
            type: 'string',
            title: 'Seo Description'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'category_id', 'slug', 'title', 'excerpt', 'body_markdown', 'cover_media_id', 'published_on', 'seo_title', 'seo_description'],
    title: 'PortfolioPostRead',
    description: 'Post response.'
} as const;

export const PortfolioPostUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1,
                    pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        excerpt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1200,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Excerpt'
        },
        body_markdown: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body Markdown'
        },
        cover_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Media Id'
        },
        published_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published On'
        },
        seo_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Title'
        },
        seo_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 320
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Description'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'PortfolioPostUpdate',
    description: 'Update one Markdown post.'
} as const;

export const PortfolioProjectCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        slug: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$',
            title: 'Slug'
        },
        title: {
            type: 'string',
            maxLength: 160,
            minLength: 1,
            title: 'Title'
        },
        summary: {
            type: 'string',
            maxLength: 1200,
            minLength: 1,
            title: 'Summary'
        },
        case_study_markdown: {
            type: 'string',
            maxLength: 100000,
            title: 'Case Study Markdown',
            default: ''
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 20,
            title: 'Tags'
        },
        media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Id'
        },
        external_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Url'
        },
        live_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Live Url'
        },
        repository_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Url'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        seo_title: {
            type: 'string',
            maxLength: 160,
            title: 'Seo Title',
            default: ''
        },
        seo_description: {
            type: 'string',
            maxLength: 320,
            title: 'Seo Description',
            default: ''
        }
    },
    type: 'object',
    required: ['slug', 'title', 'summary'],
    title: 'PortfolioProjectCreate',
    description: 'Create one project or case study.'
} as const;

export const PortfolioProjectReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        case_study_markdown: {
            type: 'string',
            title: 'Case Study Markdown'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Id'
        },
        external_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Url'
        },
        live_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Live Url'
        },
        repository_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Url'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured'
        },
        seo_title: {
            type: 'string',
            title: 'Seo Title'
        },
        seo_description: {
            type: 'string',
            title: 'Seo Description'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'slug', 'title', 'summary', 'case_study_markdown', 'tags', 'media_id', 'external_url', 'live_url', 'repository_url', 'is_featured', 'seo_title', 'seo_description'],
    title: 'PortfolioProjectRead',
    description: 'Project response.'
} as const;

export const PortfolioProjectUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1,
                    pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1200,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        case_study_markdown: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Case Study Markdown'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array',
                    maxItems: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Id'
        },
        external_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Url'
        },
        live_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Live Url'
        },
        repository_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Url'
        },
        is_featured: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Featured'
        },
        seo_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Title'
        },
        seo_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 320
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Description'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'PortfolioProjectUpdate',
    description: 'Update one project or case study.'
} as const;

export const PortfolioPublicationReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        version: {
            type: 'integer',
            title: 'Version'
        },
        checksum: {
            type: 'string',
            title: 'Checksum'
        },
        published_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Published By Id'
        },
        restored_from_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Restored From Id'
        },
        published_at: {
            type: 'string',
            format: 'date-time',
            title: 'Published At'
        }
    },
    type: 'object',
    required: ['id', 'version', 'checksum', 'published_by_id', 'restored_from_id', 'published_at'],
    title: 'PortfolioPublicationRead',
    description: 'Publication history metadata.'
} as const;

export const PortfolioServiceCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        title: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Title'
        },
        summary: {
            type: 'string',
            maxLength: 800,
            minLength: 1,
            title: 'Summary'
        },
        icon_key: {
            type: 'string',
            maxLength: 40,
            title: 'Icon Key',
            default: 'code'
        }
    },
    type: 'object',
    required: ['title', 'summary'],
    title: 'PortfolioServiceCreate',
    description: 'Create one offered service.'
} as const;

export const PortfolioServiceReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        icon_key: {
            type: 'string',
            title: 'Icon Key'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'title', 'summary', 'icon_key'],
    title: 'PortfolioServiceRead',
    description: 'Service response.'
} as const;

export const PortfolioServiceUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 800,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        icon_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Key'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'PortfolioServiceUpdate',
    description: 'Update one offered service.'
} as const;

export const PortfolioSiteReadSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        public_email: {
            type: 'string',
            title: 'Public Email'
        },
        notification_email: {
            type: 'string',
            title: 'Notification Email'
        },
        hero_summary: {
            type: 'string',
            title: 'Hero Summary'
        },
        hero_primary_label: {
            type: 'string',
            title: 'Hero Primary Label'
        },
        hero_primary_href: {
            type: 'string',
            title: 'Hero Primary Href'
        },
        hero_secondary_label: {
            type: 'string',
            title: 'Hero Secondary Label'
        },
        hero_secondary_href: {
            type: 'string',
            title: 'Hero Secondary Href'
        },
        hero_portrait_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hero Portrait Media Id'
        },
        profile_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Media Id'
        },
        about_note_title: {
            type: 'string',
            title: 'About Note Title'
        },
        about_note_summary: {
            type: 'string',
            title: 'About Note Summary'
        },
        consultation_label: {
            type: 'string',
            title: 'Consultation Label'
        },
        consultation_url: {
            type: 'string',
            title: 'Consultation Url'
        },
        consultation_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consultation Media Id'
        },
        footer_text: {
            type: 'string',
            title: 'Footer Text'
        },
        seo_title: {
            type: 'string',
            title: 'Seo Title'
        },
        seo_description: {
            type: 'string',
            title: 'Seo Description'
        },
        seo_image_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Image Media Id'
        },
        brand_logo_light_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Logo Light Media Id'
        },
        brand_logo_dark_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Logo Dark Media Id'
        },
        brand_mark_light_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Mark Light Media Id'
        },
        brand_mark_dark_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Mark Dark Media Id'
        },
        favicon_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Favicon Media Id'
        },
        brand_logo_alt: {
            type: 'string',
            title: 'Brand Logo Alt'
        },
        canonical_url: {
            type: 'string',
            title: 'Canonical Url'
        },
        robots_directive: {
            type: 'string',
            enum: ['index,follow', 'index,nofollow', 'noindex,follow', 'noindex,nofollow'],
            title: 'Robots Directive'
        },
        og_title: {
            type: 'string',
            title: 'Og Title'
        },
        og_description: {
            type: 'string',
            title: 'Og Description'
        },
        og_image_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Og Image Media Id'
        },
        twitter_card: {
            type: 'string',
            enum: ['summary', 'summary_large_image'],
            title: 'Twitter Card'
        },
        twitter_title: {
            type: 'string',
            title: 'Twitter Title'
        },
        twitter_description: {
            type: 'string',
            title: 'Twitter Description'
        },
        twitter_image_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Twitter Image Media Id'
        },
        theme_color: {
            type: 'string',
            title: 'Theme Color'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'role', 'public_email', 'notification_email', 'hero_summary', 'hero_primary_label', 'hero_primary_href', 'hero_secondary_label', 'hero_secondary_href', 'hero_portrait_media_id', 'profile_media_id', 'about_note_title', 'about_note_summary', 'consultation_label', 'consultation_url', 'consultation_media_id', 'footer_text', 'seo_title', 'seo_description', 'seo_image_media_id', 'brand_logo_light_media_id', 'brand_logo_dark_media_id', 'brand_mark_light_media_id', 'brand_mark_dark_media_id', 'favicon_media_id', 'brand_logo_alt', 'canonical_url', 'robots_directive', 'og_title', 'og_description', 'og_image_media_id', 'twitter_card', 'twitter_title', 'twitter_description', 'twitter_image_media_id', 'theme_color', 'updated_at'],
    title: 'PortfolioSiteRead',
    description: 'Global draft portfolio settings.'
} as const;

export const PortfolioSiteUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        role: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        },
        public_email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Email'
        },
        notification_email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notification Email'
        },
        hero_summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1200,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hero Summary'
        },
        hero_primary_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 60,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hero Primary Label'
        },
        hero_primary_href: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hero Primary Href'
        },
        hero_secondary_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 60,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hero Secondary Label'
        },
        hero_secondary_href: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hero Secondary Href'
        },
        hero_portrait_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hero Portrait Media Id'
        },
        profile_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Media Id'
        },
        about_note_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'About Note Title'
        },
        about_note_summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'About Note Summary'
        },
        consultation_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consultation Label'
        },
        consultation_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consultation Url'
        },
        consultation_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consultation Media Id'
        },
        footer_text: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 240
                },
                {
                    type: 'null'
                }
            ],
            title: 'Footer Text'
        },
        seo_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Title'
        },
        seo_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 320
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Description'
        },
        seo_image_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seo Image Media Id'
        },
        brand_logo_light_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Logo Light Media Id'
        },
        brand_logo_dark_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Logo Dark Media Id'
        },
        brand_mark_light_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Mark Light Media Id'
        },
        brand_mark_dark_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Mark Dark Media Id'
        },
        favicon_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Favicon Media Id'
        },
        brand_logo_alt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Logo Alt'
        },
        canonical_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Canonical Url'
        },
        robots_directive: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['index,follow', 'index,nofollow', 'noindex,follow', 'noindex,nofollow']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Robots Directive'
        },
        og_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Og Title'
        },
        og_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 320
                },
                {
                    type: 'null'
                }
            ],
            title: 'Og Description'
        },
        og_image_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Og Image Media Id'
        },
        twitter_card: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['summary', 'summary_large_image']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Twitter Card'
        },
        twitter_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 160
                },
                {
                    type: 'null'
                }
            ],
            title: 'Twitter Title'
        },
        twitter_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 320
                },
                {
                    type: 'null'
                }
            ],
            title: 'Twitter Description'
        },
        twitter_image_media_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Twitter Image Media Id'
        },
        theme_color: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^#[0-9A-Fa-f]{6}$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Theme Color'
        }
    },
    type: 'object',
    title: 'PortfolioSiteUpdate',
    description: 'Partial update for global draft settings.'
} as const;

export const PostCategoryCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        name: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$',
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['name', 'slug'],
    title: 'PostCategoryCreate',
    description: 'Create one post category.'
} as const;

export const PostCategoryReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'name', 'slug'],
    title: 'PostCategoryRead',
    description: 'Post-category response.'
} as const;

export const PostCategoryUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80,
                    minLength: 1,
                    pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'PostCategoryUpdate',
    description: 'Update one post category.'
} as const;

export const ProfileUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'ProfileUpdate',
    description: "Payload for updating the current user's profile."
} as const;

export const PublishedPostDetailSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        excerpt: {
            type: 'string',
            title: 'Excerpt'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        date: {
            type: 'string',
            title: 'Date'
        },
        href: {
            type: 'string',
            title: 'Href'
        },
        body_markdown: {
            type: 'string',
            title: 'Body Markdown'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        seo_title: {
            type: 'string',
            title: 'Seo Title',
            default: ''
        },
        seo_description: {
            type: 'string',
            title: 'Seo Description',
            default: ''
        }
    },
    type: 'object',
    required: ['slug', 'title', 'excerpt', 'category', 'date', 'href', 'body_markdown'],
    title: 'PublishedPostDetail',
    description: 'Full post detail from the current publication.'
} as const;

export const PublishedPostSummarySchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        excerpt: {
            type: 'string',
            title: 'Excerpt'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        date: {
            type: 'string',
            title: 'Date'
        },
        href: {
            type: 'string',
            title: 'Href'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'excerpt', 'category', 'date', 'href'],
    title: 'PublishedPostSummary',
    description: 'Post list item from the current publication.'
} as const;

export const PublishedProjectDetailSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        case_study_markdown: {
            type: 'string',
            title: 'Case Study Markdown'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        live_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Live Url'
        },
        repository_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Url'
        },
        seo_title: {
            type: 'string',
            title: 'Seo Title',
            default: ''
        },
        seo_description: {
            type: 'string',
            title: 'Seo Description',
            default: ''
        }
    },
    type: 'object',
    required: ['slug', 'title', 'summary', 'case_study_markdown', 'tags'],
    title: 'PublishedProjectDetail',
    description: 'Full internal project case study from the current publication.'
} as const;

export const RoleAssignmentSchema = {
    properties: {
        role_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Role Names'
        }
    },
    type: 'object',
    required: ['role_names'],
    title: 'RoleAssignment',
    description: 'Payload for assigning roles to a user.'
} as const;

export const RoleReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        permissions: {
            items: {
                '$ref': '#/components/schemas/PermissionRead'
            },
            type: 'array',
            title: 'Permissions',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'name', 'description'],
    title: 'RoleRead',
    description: 'Role data with attached permissions.'
} as const;

export const SectionSettingReadSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        heading: {
            type: 'string',
            title: 'Heading'
        },
        navigation_label: {
            type: 'string',
            title: 'Navigation Label'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['key', 'heading', 'navigation_label', 'summary', 'is_visible', 'updated_at'],
    title: 'SectionSettingRead',
    description: 'Editable section heading and navigation metadata.'
} as const;

export const SectionSettingUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        heading: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Heading'
        },
        navigation_label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Navigation Label'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'SectionSettingUpdate',
    description: 'Partial section-setting update.'
} as const;

export const SocialLinkCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        platform: {
            type: 'string',
            maxLength: 60,
            minLength: 1,
            title: 'Platform'
        },
        label: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Label'
        },
        url: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Url'
        },
        icon_key: {
            type: 'string',
            maxLength: 40,
            minLength: 1,
            title: 'Icon Key'
        }
    },
    type: 'object',
    required: ['platform', 'label', 'url', 'icon_key'],
    title: 'SocialLinkCreate',
    description: 'Create one social link.'
} as const;

export const SocialLinkReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        platform: {
            type: 'string',
            title: 'Platform'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        icon_key: {
            type: 'string',
            title: 'Icon Key'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'platform', 'label', 'url', 'icon_key'],
    title: 'SocialLinkRead',
    description: 'Social-link response.'
} as const;

export const SocialLinkUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        platform: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 60,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Platform'
        },
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        icon_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Icon Key'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'SocialLinkUpdate',
    description: 'Update one social link.'
} as const;

export const StackUseCaseSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Title'
        },
        summary: {
            type: 'string',
            maxLength: 300,
            minLength: 1,
            title: 'Summary'
        }
    },
    type: 'object',
    required: ['title', 'summary'],
    title: 'StackUseCase',
    description: 'Compact stack use case shown beneath a code sample.'
} as const;

export const TechnologyStackCreateSchema = {
    properties: {
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible',
            default: true
        },
        language: {
            type: 'string',
            maxLength: 80,
            minLength: 1,
            title: 'Language'
        },
        summary: {
            type: 'string',
            maxLength: 800,
            minLength: 1,
            title: 'Summary'
        },
        code_snippet: {
            type: 'string',
            maxLength: 10000,
            minLength: 1,
            title: 'Code Snippet'
        },
        tools: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 20,
            title: 'Tools'
        },
        use_cases: {
            items: {
                '$ref': '#/components/schemas/StackUseCase'
            },
            type: 'array',
            maxItems: 8,
            title: 'Use Cases'
        }
    },
    type: 'object',
    required: ['language', 'summary', 'code_snippet'],
    title: 'TechnologyStackCreate',
    description: 'Create one technology stack.'
} as const;

export const TechnologyStackReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_visible: {
            type: 'boolean',
            title: 'Is Visible'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        language: {
            type: 'string',
            title: 'Language'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        code_snippet: {
            type: 'string',
            title: 'Code Snippet'
        },
        tools: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tools'
        },
        use_cases: {
            items: {
                additionalProperties: {
                    type: 'string'
                },
                type: 'object'
            },
            type: 'array',
            title: 'Use Cases'
        }
    },
    type: 'object',
    required: ['id', 'sort_order', 'is_visible', 'is_archived', 'created_at', 'updated_at', 'language', 'summary', 'code_snippet', 'tools', 'use_cases'],
    title: 'TechnologyStackRead',
    description: 'Technology-stack response.'
} as const;

export const TechnologyStackUpdateSchema = {
    properties: {
        expected_updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Updated At'
        },
        language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        },
        summary: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 800,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        code_snippet: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code Snippet'
        },
        tools: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array',
                    maxItems: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tools'
        },
        use_cases: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/StackUseCase'
                    },
                    type: 'array',
                    maxItems: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Use Cases'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        is_visible: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Visible'
        }
    },
    type: 'object',
    title: 'TechnologyStackUpdate',
    description: 'Update one technology stack.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Payload for creating a self-service user account.'
} as const;

export const UserListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UserList',
    description: 'Paginated user list response.'
} as const;

export const UserReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        roles: {
            items: {
                '$ref': '#/components/schemas/RoleRead'
            },
            type: 'array',
            title: 'Roles',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'email', 'is_active'],
    title: 'UserRead',
    description: 'Public user data returned by account and admin endpoints.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const app__portfolio__schemas__MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Simple portfolio domain operation response.'
} as const;

export const app__schemas__MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;