// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthApiV1HealthGetResponse, StatusApiV1HealthStatusGetResponse, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostResponse, SignupApiV1AuthSignupPostData, SignupApiV1AuthSignupPostResponse, RefreshApiV1AuthRefreshPostData, RefreshApiV1AuthRefreshPostResponse, LogoutApiV1AuthLogoutPostData, LogoutApiV1AuthLogoutPostResponse, MeApiV1AuthMeGetData, MeApiV1AuthMeGetResponse, UpdateMeApiV1AuthMePatchData, UpdateMeApiV1AuthMePatchResponse, DeleteMeApiV1AuthMeDeleteData, DeleteMeApiV1AuthMeDeleteResponse, ChangePasswordApiV1AuthMePasswordPostData, ChangePasswordApiV1AuthMePasswordPostResponse, RecoverPasswordApiV1AuthPasswordRecoveryPostData, RecoverPasswordApiV1AuthPasswordRecoveryPostResponse, ResetPasswordApiV1AuthResetPasswordPostData, ResetPasswordApiV1AuthResetPasswordPostResponse, ListUsersApiV1AdminUsersGetData, ListUsersApiV1AdminUsersGetResponse, CreateUserApiV1AdminUsersPostData, CreateUserApiV1AdminUsersPostResponse, AssignRolesApiV1AdminUsersUserIdRolesPatchData, AssignRolesApiV1AdminUsersUserIdRolesPatchResponse, UpdateUserApiV1AdminUsersUserIdPatchData, UpdateUserApiV1AdminUsersUserIdPatchResponse, DeleteUserApiV1AdminUsersUserIdDeleteData, DeleteUserApiV1AdminUsersUserIdDeleteResponse, ListRolesApiV1AdminRolesGetData, ListRolesApiV1AdminRolesGetResponse, ListItemsApiV1ItemsGetData, ListItemsApiV1ItemsGetResponse, CreateItemApiV1ItemsPostData, CreateItemApiV1ItemsPostResponse, ReadItemApiV1ItemsItemIdGetData, ReadItemApiV1ItemsItemIdGetResponse, UpdateItemApiV1ItemsItemIdPatchData, UpdateItemApiV1ItemsItemIdPatchResponse, DeleteItemApiV1ItemsItemIdDeleteData, DeleteItemApiV1ItemsItemIdDeleteResponse } from './types.gen';

/**
 * Health
 * Return a minimal liveness response.
 * @returns string Successful Response
 * @throws ApiError
 */
export const healthApiV1HealthGet = (): CancelablePromise<HealthApiV1HealthGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/health'
    });
};

/**
 * Status
 * Return app, database, and optional Redis status.
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const statusApiV1HealthStatusGet = (): CancelablePromise<StatusApiV1HealthStatusGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/health/status'
    });
};

/**
 * Login
 * Authenticate a user and issue cookie-backed session tokens.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const loginApiV1AuthLoginPost = (data: LoginApiV1AuthLoginPostData): CancelablePromise<LoginApiV1AuthLoginPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/auth/login',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Signup
 * Create a user account when signup is enabled.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const signupApiV1AuthSignupPost = (data: SignupApiV1AuthSignupPostData): CancelablePromise<SignupApiV1AuthSignupPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/auth/signup',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Refresh
 * Rotate the access and refresh cookies from a valid refresh token.
 * @param data The data for the request.
 * @param data.refreshToken
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const refreshApiV1AuthRefreshPost = (data: RefreshApiV1AuthRefreshPostData = {}): CancelablePromise<RefreshApiV1AuthRefreshPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/auth/refresh',
        cookies: {
            refresh_token: data.refreshToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Logout
 * Revoke the current session and clear auth cookies.
 * @param data The data for the request.
 * @param data.csrfToken
 * @param data.accessToken
 * @returns string Successful Response
 * @throws ApiError
 */
export const logoutApiV1AuthLogoutPost = (data: LogoutApiV1AuthLogoutPostData = {}): CancelablePromise<LogoutApiV1AuthLogoutPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/auth/logout',
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Me
 * Return the current authenticated user.
 * @param data The data for the request.
 * @param data.accessToken
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const meApiV1AuthMeGet = (data: MeApiV1AuthMeGetData = {}): CancelablePromise<MeApiV1AuthMeGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/auth/me',
        cookies: {
            access_token: data.accessToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Update Me
 * Update the current user's profile and email address.
 * @param data The data for the request.
 * @param data.requestBody
 * @param data.csrfToken
 * @param data.accessToken
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const updateMeApiV1AuthMePatch = (data: UpdateMeApiV1AuthMePatchData): CancelablePromise<UpdateMeApiV1AuthMePatchResponse> => {
    return __request(OpenAPI, {
        method: 'PATCH',
        url: '/api/v1/auth/me',
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Delete Me
 * Delete the current non-admin account and owned items.
 * @param data The data for the request.
 * @param data.csrfToken
 * @param data.accessToken
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteMeApiV1AuthMeDelete = (data: DeleteMeApiV1AuthMeDeleteData = {}): CancelablePromise<DeleteMeApiV1AuthMeDeleteResponse> => {
    return __request(OpenAPI, {
        method: 'DELETE',
        url: '/api/v1/auth/me',
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Change Password
 * Change the current user's password and revoke active sessions.
 * @param data The data for the request.
 * @param data.requestBody
 * @param data.csrfToken
 * @param data.accessToken
 * @returns string Successful Response
 * @throws ApiError
 */
export const changePasswordApiV1AuthMePasswordPost = (data: ChangePasswordApiV1AuthMePasswordPostData): CancelablePromise<ChangePasswordApiV1AuthMePasswordPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/auth/me/password',
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Recover Password
 * Send a password recovery email without revealing account existence.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Message Successful Response
 * @throws ApiError
 */
export const recoverPasswordApiV1AuthPasswordRecoveryPost = (data: RecoverPasswordApiV1AuthPasswordRecoveryPostData): CancelablePromise<RecoverPasswordApiV1AuthPasswordRecoveryPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/auth/password-recovery',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Reset Password
 * Reset a user's password from a valid recovery token.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Message Successful Response
 * @throws ApiError
 */
export const resetPasswordApiV1AuthResetPasswordPost = (data: ResetPasswordApiV1AuthResetPasswordPostData): CancelablePromise<ResetPasswordApiV1AuthResetPasswordPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/auth/reset-password',
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Users
 * List users for the admin table.
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @param data.accessToken
 * @returns UserList Successful Response
 * @throws ApiError
 */
export const listUsersApiV1AdminUsersGet = (data: ListUsersApiV1AdminUsersGetData = {}): CancelablePromise<ListUsersApiV1AdminUsersGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/admin/users',
        cookies: {
            access_token: data.accessToken
        },
        query: {
            skip: data.skip,
            limit: data.limit
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Create User
 * Create a user from the admin interface.
 * @param data The data for the request.
 * @param data.requestBody
 * @param data.csrfToken
 * @param data.accessToken
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const createUserApiV1AdminUsersPost = (data: CreateUserApiV1AdminUsersPostData): CancelablePromise<CreateUserApiV1AdminUsersPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/admin/users',
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Assign Roles
 * Replace a user's roles.
 * @param data The data for the request.
 * @param data.userId
 * @param data.requestBody
 * @param data.csrfToken
 * @param data.accessToken
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const assignRolesApiV1AdminUsersUserIdRolesPatch = (data: AssignRolesApiV1AdminUsersUserIdRolesPatchData): CancelablePromise<AssignRolesApiV1AdminUsersUserIdRolesPatchResponse> => {
    return __request(OpenAPI, {
        method: 'PATCH',
        url: '/api/v1/admin/users/{user_id}/roles',
        path: {
            user_id: data.userId
        },
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Update User
 * Update a user's profile, password, activation, or roles.
 * @param data The data for the request.
 * @param data.userId
 * @param data.requestBody
 * @param data.csrfToken
 * @param data.accessToken
 * @returns UserRead Successful Response
 * @throws ApiError
 */
export const updateUserApiV1AdminUsersUserIdPatch = (data: UpdateUserApiV1AdminUsersUserIdPatchData): CancelablePromise<UpdateUserApiV1AdminUsersUserIdPatchResponse> => {
    return __request(OpenAPI, {
        method: 'PATCH',
        url: '/api/v1/admin/users/{user_id}',
        path: {
            user_id: data.userId
        },
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Delete User
 * Delete a user and their owned items.
 * @param data The data for the request.
 * @param data.userId
 * @param data.csrfToken
 * @param data.accessToken
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteUserApiV1AdminUsersUserIdDelete = (data: DeleteUserApiV1AdminUsersUserIdDeleteData): CancelablePromise<DeleteUserApiV1AdminUsersUserIdDeleteResponse> => {
    return __request(OpenAPI, {
        method: 'DELETE',
        url: '/api/v1/admin/users/{user_id}',
        path: {
            user_id: data.userId
        },
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Roles
 * List all built-in roles.
 * @param data The data for the request.
 * @param data.accessToken
 * @returns RoleRead Successful Response
 * @throws ApiError
 */
export const listRolesApiV1AdminRolesGet = (data: ListRolesApiV1AdminRolesGetData = {}): CancelablePromise<ListRolesApiV1AdminRolesGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/admin/roles',
        cookies: {
            access_token: data.accessToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * List Items
 * List items visible to the current user.
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @param data.accessToken
 * @returns ItemList Successful Response
 * @throws ApiError
 */
export const listItemsApiV1ItemsGet = (data: ListItemsApiV1ItemsGetData = {}): CancelablePromise<ListItemsApiV1ItemsGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/items',
        cookies: {
            access_token: data.accessToken
        },
        query: {
            skip: data.skip,
            limit: data.limit
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Create Item
 * Create an item owned by the current user.
 * @param data The data for the request.
 * @param data.requestBody
 * @param data.csrfToken
 * @param data.accessToken
 * @returns ItemRead Successful Response
 * @throws ApiError
 */
export const createItemApiV1ItemsPost = (data: CreateItemApiV1ItemsPostData): CancelablePromise<CreateItemApiV1ItemsPostResponse> => {
    return __request(OpenAPI, {
        method: 'POST',
        url: '/api/v1/items',
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Read Item
 * Read one item when visible to the current user.
 * @param data The data for the request.
 * @param data.itemId
 * @param data.accessToken
 * @returns ItemRead Successful Response
 * @throws ApiError
 */
export const readItemApiV1ItemsItemIdGet = (data: ReadItemApiV1ItemsItemIdGetData): CancelablePromise<ReadItemApiV1ItemsItemIdGetResponse> => {
    return __request(OpenAPI, {
        method: 'GET',
        url: '/api/v1/items/{item_id}',
        path: {
            item_id: data.itemId
        },
        cookies: {
            access_token: data.accessToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Update Item
 * Update one item when writable by the current user.
 * @param data The data for the request.
 * @param data.itemId
 * @param data.requestBody
 * @param data.csrfToken
 * @param data.accessToken
 * @returns ItemRead Successful Response
 * @throws ApiError
 */
export const updateItemApiV1ItemsItemIdPatch = (data: UpdateItemApiV1ItemsItemIdPatchData): CancelablePromise<UpdateItemApiV1ItemsItemIdPatchResponse> => {
    return __request(OpenAPI, {
        method: 'PATCH',
        url: '/api/v1/items/{item_id}',
        path: {
            item_id: data.itemId
        },
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        body: data.requestBody,
        mediaType: 'application/json',
        errors: {
            422: 'Validation Error'
        }
    });
};

/**
 * Delete Item
 * Delete one item when writable by the current user.
 * @param data The data for the request.
 * @param data.itemId
 * @param data.csrfToken
 * @param data.accessToken
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteItemApiV1ItemsItemIdDelete = (data: DeleteItemApiV1ItemsItemIdDeleteData): CancelablePromise<DeleteItemApiV1ItemsItemIdDeleteResponse> => {
    return __request(OpenAPI, {
        method: 'DELETE',
        url: '/api/v1/items/{item_id}',
        path: {
            item_id: data.itemId
        },
        cookies: {
            csrf_token: data.csrfToken,
            access_token: data.accessToken
        },
        errors: {
            422: 'Validation Error'
        }
    });
};