// This file is auto-generated by @hey-api/openapi-ts

/**
 * Create one About bento card.
 */
export type AboutCardCreate = {
    sort_order?: number;
    is_visible?: boolean;
    title: string;
    summary: string;
    media_id?: (string | null);
    image_alt?: string;
    layout?: 'tall' | 'wide' | 'small';
    tone?: 'navy' | 'white' | 'blue' | 'orange';
    image_fit?: 'contain' | 'cover';
    image_ratio?: ('portrait' | 'landscape' | null);
};

export type layout = 'tall' | 'wide' | 'small';

export type tone = 'navy' | 'white' | 'blue' | 'orange';

export type image_fit = 'contain' | 'cover';

/**
 * About-card response.
 */
export type AboutCardRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    title: string;
    summary: string;
    media_id: (string | null);
    image_alt: string;
    layout: string;
    tone: string;
    image_fit: string;
    image_ratio: (string | null);
};

/**
 * Update one About bento card.
 */
export type AboutCardUpdate = {
    expected_updated_at?: (string | null);
    title?: (string | null);
    summary?: (string | null);
    media_id?: (string | null);
    image_alt?: (string | null);
    layout?: ('tall' | 'wide' | 'small' | null);
    tone?: ('navy' | 'white' | 'blue' | 'orange' | null);
    image_fit?: ('contain' | 'cover' | null);
    image_ratio?: ('portrait' | 'landscape' | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

/**
 * Payload for creating a user from the admin interface.
 */
export type AdminUserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    role_names?: Array<(string)>;
};

/**
 * Payload for admin-managed user updates.
 */
export type AdminUserUpdate = {
    email?: (string | null);
    full_name?: (string | null);
    password?: (string | null);
    is_active?: (boolean | null);
    role_names?: (Array<(string)> | null);
};

/**
 * Simple portfolio domain operation response.
 */
export type app__portfolio__schemas__Message = {
    message: string;
};

/**
 * Generic message response.
 */
export type app__schemas__Message = {
    message: string;
};

export type Body_upload_media_api_v1_admin_portfolio_media_post = {
    file: string;
    alt_text?: string;
};

/**
 * Atomic ordered-ID replacement for one collection.
 */
export type CollectionOrderUpdate = {
    ids: Array<(string)>;
};

/**
 * Non-sensitive public acknowledgement for a stored enquiry.
 */
export type ContactAccepted = {
    status?: "accepted";
};

/**
 * Public contact enquiry including an invisible bot trap.
 */
export type ContactCreate = {
    name: string;
    email: string;
    subject: string;
    message: string;
    company?: string;
};

/**
 * Contact inbox response.
 */
export type ContactSubmissionRead = {
    id: string;
    name: string;
    email: string;
    subject: string;
    message: string;
    inbox_state: string;
    delivery_state: string;
    delivery_attempts: number;
    last_delivery_at: (string | null);
    delivered_at: (string | null);
    delivery_error: (string | null);
    is_archived: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Update inbox state or archive status.
 */
export type ContactSubmissionUpdate = {
    expected_updated_at?: (string | null);
    inbox_state?: ('new' | 'read' | 'replied' | 'spam' | 'archived' | null);
    is_archived?: (boolean | null);
};

/**
 * Create one hero expertise entry.
 */
export type HeroExpertiseCreate = {
    sort_order?: number;
    is_visible?: boolean;
    label: string;
    icon_key: string;
};

/**
 * Hero expertise response.
 */
export type HeroExpertiseRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    label: string;
    icon_key: string;
};

/**
 * Update one hero expertise entry.
 */
export type HeroExpertiseUpdate = {
    expected_updated_at?: (string | null);
    label?: (string | null);
    icon_key?: (string | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Payload for creating an item.
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Paginated item list response.
 */
export type ItemList = {
    data: Array<ItemRead>;
    count: number;
};

/**
 * Item data returned by item endpoints.
 */
export type ItemRead = {
    id: string;
    title: string;
    description?: (string | null);
    owner_id: string;
};

/**
 * Payload for updating an item.
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Email and password login payload.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Media metadata without binary bytes.
 */
export type MediaAssetRead = {
    id: string;
    filename: string;
    mime_type: string;
    size_bytes: number;
    width: (number | null);
    height: (number | null);
    checksum: string;
    alt_text: string;
    storage_kind: string;
    static_path: (string | null);
    local_path: (string | null);
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    url?: (string | null);
};

/**
 * Editable media metadata.
 */
export type MediaAssetUpdate = {
    expected_updated_at?: (string | null);
    filename?: (string | null);
    alt_text?: (string | null);
    is_archived?: (boolean | null);
};

/**
 * Payload for changing the current user's password.
 */
export type PasswordChange = {
    current_password: string;
    new_password: string;
};

/**
 * Payload for requesting a password recovery email.
 */
export type PasswordRecoveryRequest = {
    email: string;
};

/**
 * Payload for completing password reset with a token.
 */
export type PasswordResetRequest = {
    token: string;
    new_password: string;
};

/**
 * Permission data exposed to the frontend.
 */
export type PermissionRead = {
    code: string;
    description: string;
};

/**
 * Published or preview aggregate response.
 */
export type PortfolioContentResponse = {
    publication?: (PortfolioPublicationRead | null);
    content?: ({
    [key: string]: unknown;
} | null);
    source: 'published' | 'draft' | 'none';
};

export type source = 'published' | 'draft' | 'none';

/**
 * Create one Markdown post.
 */
export type PortfolioPostCreate = {
    sort_order?: number;
    is_visible?: boolean;
    category_id: string;
    slug: string;
    title: string;
    excerpt: string;
    body_markdown?: string;
    cover_media_id?: (string | null);
    published_on?: (string | null);
    seo_title?: string;
    seo_description?: string;
};

/**
 * Post response.
 */
export type PortfolioPostRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    category_id: string;
    slug: string;
    title: string;
    excerpt: string;
    body_markdown: string;
    cover_media_id: (string | null);
    published_on: (string | null);
    seo_title: string;
    seo_description: string;
};

/**
 * Update one Markdown post.
 */
export type PortfolioPostUpdate = {
    expected_updated_at?: (string | null);
    category_id?: (string | null);
    slug?: (string | null);
    title?: (string | null);
    excerpt?: (string | null);
    body_markdown?: (string | null);
    cover_media_id?: (string | null);
    published_on?: (string | null);
    seo_title?: (string | null);
    seo_description?: (string | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

/**
 * Create one project or case study.
 */
export type PortfolioProjectCreate = {
    sort_order?: number;
    is_visible?: boolean;
    slug: string;
    title: string;
    summary: string;
    case_study_markdown?: string;
    tags?: Array<(string)>;
    media_id?: (string | null);
    external_url?: (string | null);
    live_url?: (string | null);
    repository_url?: (string | null);
    is_featured?: boolean;
    seo_title?: string;
    seo_description?: string;
};

/**
 * Project response.
 */
export type PortfolioProjectRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    slug: string;
    title: string;
    summary: string;
    case_study_markdown: string;
    tags: Array<(string)>;
    media_id: (string | null);
    external_url: (string | null);
    live_url: (string | null);
    repository_url: (string | null);
    is_featured: boolean;
    seo_title: string;
    seo_description: string;
};

/**
 * Update one project or case study.
 */
export type PortfolioProjectUpdate = {
    expected_updated_at?: (string | null);
    slug?: (string | null);
    title?: (string | null);
    summary?: (string | null);
    case_study_markdown?: (string | null);
    tags?: (Array<(string)> | null);
    media_id?: (string | null);
    external_url?: (string | null);
    live_url?: (string | null);
    repository_url?: (string | null);
    is_featured?: (boolean | null);
    seo_title?: (string | null);
    seo_description?: (string | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

/**
 * Publication history metadata.
 */
export type PortfolioPublicationRead = {
    id: string;
    version: number;
    checksum: string;
    published_by_id: string;
    restored_from_id: (string | null);
    published_at: string;
};

/**
 * Create one offered service.
 */
export type PortfolioServiceCreate = {
    sort_order?: number;
    is_visible?: boolean;
    title: string;
    summary: string;
    icon_key?: string;
};

/**
 * Service response.
 */
export type PortfolioServiceRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    title: string;
    summary: string;
    icon_key: string;
};

/**
 * Update one offered service.
 */
export type PortfolioServiceUpdate = {
    expected_updated_at?: (string | null);
    title?: (string | null);
    summary?: (string | null);
    icon_key?: (string | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

/**
 * Global draft portfolio settings.
 */
export type PortfolioSiteRead = {
    id: string;
    name: string;
    role: string;
    public_email: string;
    notification_email: string;
    hero_summary: string;
    hero_primary_label: string;
    hero_primary_href: string;
    hero_secondary_label: string;
    hero_secondary_href: string;
    hero_portrait_media_id: (string | null);
    profile_media_id: (string | null);
    about_note_title: string;
    about_note_summary: string;
    consultation_label: string;
    consultation_url: string;
    consultation_media_id: (string | null);
    footer_text: string;
    seo_title: string;
    seo_description: string;
    seo_image_media_id: (string | null);
    brand_logo_light_media_id: (string | null);
    brand_logo_dark_media_id: (string | null);
    brand_mark_light_media_id: (string | null);
    brand_mark_dark_media_id: (string | null);
    favicon_media_id: (string | null);
    brand_logo_alt: string;
    canonical_url: string;
    robots_directive: 'index,follow' | 'index,nofollow' | 'noindex,follow' | 'noindex,nofollow';
    og_title: string;
    og_description: string;
    og_image_media_id: (string | null);
    twitter_card: 'summary' | 'summary_large_image';
    twitter_title: string;
    twitter_description: string;
    twitter_image_media_id: (string | null);
    theme_color: string;
    updated_at: string;
};

export type robots_directive = 'index,follow' | 'index,nofollow' | 'noindex,follow' | 'noindex,nofollow';

export type twitter_card = 'summary' | 'summary_large_image';

/**
 * Partial update for global draft settings.
 */
export type PortfolioSiteUpdate = {
    expected_updated_at?: (string | null);
    name?: (string | null);
    role?: (string | null);
    public_email?: (string | null);
    notification_email?: (string | null);
    hero_summary?: (string | null);
    hero_primary_label?: (string | null);
    hero_primary_href?: (string | null);
    hero_secondary_label?: (string | null);
    hero_secondary_href?: (string | null);
    hero_portrait_media_id?: (string | null);
    profile_media_id?: (string | null);
    about_note_title?: (string | null);
    about_note_summary?: (string | null);
    consultation_label?: (string | null);
    consultation_url?: (string | null);
    consultation_media_id?: (string | null);
    footer_text?: (string | null);
    seo_title?: (string | null);
    seo_description?: (string | null);
    seo_image_media_id?: (string | null);
    brand_logo_light_media_id?: (string | null);
    brand_logo_dark_media_id?: (string | null);
    brand_mark_light_media_id?: (string | null);
    brand_mark_dark_media_id?: (string | null);
    favicon_media_id?: (string | null);
    brand_logo_alt?: (string | null);
    canonical_url?: (string | null);
    robots_directive?: ('index,follow' | 'index,nofollow' | 'noindex,follow' | 'noindex,nofollow' | null);
    og_title?: (string | null);
    og_description?: (string | null);
    og_image_media_id?: (string | null);
    twitter_card?: ('summary' | 'summary_large_image' | null);
    twitter_title?: (string | null);
    twitter_description?: (string | null);
    twitter_image_media_id?: (string | null);
    theme_color?: (string | null);
};

/**
 * Create one post category.
 */
export type PostCategoryCreate = {
    sort_order?: number;
    is_visible?: boolean;
    name: string;
    slug: string;
};

/**
 * Post-category response.
 */
export type PostCategoryRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    name: string;
    slug: string;
};

/**
 * Update one post category.
 */
export type PostCategoryUpdate = {
    expected_updated_at?: (string | null);
    name?: (string | null);
    slug?: (string | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

/**
 * Payload for updating the current user's profile.
 */
export type ProfileUpdate = {
    full_name?: (string | null);
    email?: (string | null);
};

/**
 * Full post detail from the current publication.
 */
export type PublishedPostDetail = {
    slug: string;
    title: string;
    excerpt: string;
    category: string;
    date: string;
    href: string;
    body_markdown: string;
    cover_image?: (string | null);
    seo_title?: string;
    seo_description?: string;
};

/**
 * Post list item from the current publication.
 */
export type PublishedPostSummary = {
    slug: string;
    title: string;
    excerpt: string;
    category: string;
    date: string;
    href: string;
};

/**
 * Full internal project case study from the current publication.
 */
export type PublishedProjectDetail = {
    slug: string;
    title: string;
    summary: string;
    case_study_markdown: string;
    tags: Array<(string)>;
    image?: (string | null);
    live_url?: (string | null);
    repository_url?: (string | null);
    seo_title?: string;
    seo_description?: string;
};

/**
 * Payload for assigning roles to a user.
 */
export type RoleAssignment = {
    role_names: Array<(string)>;
};

/**
 * Role data with attached permissions.
 */
export type RoleRead = {
    id: string;
    name: string;
    description: string;
    permissions?: Array<PermissionRead>;
};

/**
 * Editable section heading and navigation metadata.
 */
export type SectionSettingRead = {
    key: string;
    heading: string;
    navigation_label: string;
    summary: (string | null);
    is_visible: boolean;
    updated_at: string;
};

/**
 * Partial section-setting update.
 */
export type SectionSettingUpdate = {
    expected_updated_at?: (string | null);
    heading?: (string | null);
    navigation_label?: (string | null);
    summary?: (string | null);
    is_visible?: (boolean | null);
};

/**
 * Create one social link.
 */
export type SocialLinkCreate = {
    sort_order?: number;
    is_visible?: boolean;
    platform: string;
    label: string;
    url: string;
    icon_key: string;
};

/**
 * Social-link response.
 */
export type SocialLinkRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    platform: string;
    label: string;
    url: string;
    icon_key: string;
};

/**
 * Update one social link.
 */
export type SocialLinkUpdate = {
    expected_updated_at?: (string | null);
    platform?: (string | null);
    label?: (string | null);
    url?: (string | null);
    icon_key?: (string | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

/**
 * Compact stack use case shown beneath a code sample.
 */
export type StackUseCase = {
    title: string;
    summary: string;
};

/**
 * Create one technology stack.
 */
export type TechnologyStackCreate = {
    sort_order?: number;
    is_visible?: boolean;
    language: string;
    summary: string;
    code_snippet: string;
    tools?: Array<(string)>;
    use_cases?: Array<StackUseCase>;
};

/**
 * Technology-stack response.
 */
export type TechnologyStackRead = {
    id: string;
    sort_order: number;
    is_visible: boolean;
    is_archived: boolean;
    created_at: string;
    updated_at: string;
    language: string;
    summary: string;
    code_snippet: string;
    tools: Array<(string)>;
    use_cases: Array<{
        [key: string]: (string);
    }>;
};

/**
 * Update one technology stack.
 */
export type TechnologyStackUpdate = {
    expected_updated_at?: (string | null);
    language?: (string | null);
    summary?: (string | null);
    code_snippet?: (string | null);
    tools?: (Array<(string)> | null);
    use_cases?: (Array<StackUseCase> | null);
    sort_order?: (number | null);
    is_visible?: (boolean | null);
};

/**
 * Payload for creating a self-service user account.
 */
export type UserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Paginated user list response.
 */
export type UserList = {
    data: Array<UserRead>;
    count: number;
};

/**
 * Public user data returned by account and admin endpoints.
 */
export type UserRead = {
    id: string;
    email: string;
    full_name?: (string | null);
    is_active: boolean;
    roles?: Array<RoleRead>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthApiV1HealthGetResponse = ({
    [key: string]: (string);
});

export type StatusApiV1HealthStatusGetResponse = ({
    [key: string]: unknown;
});

export type LoginApiV1AuthLoginPostData = {
    requestBody: LoginRequest;
};

export type LoginApiV1AuthLoginPostResponse = (UserRead);

export type SignupApiV1AuthSignupPostData = {
    requestBody: UserCreate;
};

export type SignupApiV1AuthSignupPostResponse = (UserRead);

export type RefreshApiV1AuthRefreshPostData = {
    refreshToken?: (string | null);
};

export type RefreshApiV1AuthRefreshPostResponse = (UserRead);

export type LogoutApiV1AuthLogoutPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
};

export type LogoutApiV1AuthLogoutPostResponse = ({
    [key: string]: (string);
});

export type MeApiV1AuthMeGetData = {
    accessToken?: (string | null);
};

export type MeApiV1AuthMeGetResponse = ((UserRead | null));

export type UpdateMeApiV1AuthMePatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: ProfileUpdate;
};

export type UpdateMeApiV1AuthMePatchResponse = (UserRead);

export type DeleteMeApiV1AuthMeDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
};

export type DeleteMeApiV1AuthMeDeleteResponse = (app__schemas__Message);

export type ChangePasswordApiV1AuthMePasswordPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: PasswordChange;
};

export type ChangePasswordApiV1AuthMePasswordPostResponse = ({
    [key: string]: (string);
});

export type RecoverPasswordApiV1AuthPasswordRecoveryPostData = {
    requestBody: PasswordRecoveryRequest;
};

export type RecoverPasswordApiV1AuthPasswordRecoveryPostResponse = (app__schemas__Message);

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    requestBody: PasswordResetRequest;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = (app__schemas__Message);

export type ListUsersApiV1AdminUsersGetData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListUsersApiV1AdminUsersGetResponse = (UserList);

export type CreateUserApiV1AdminUsersPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: AdminUserCreate;
};

export type CreateUserApiV1AdminUsersPostResponse = (UserRead);

export type AssignRolesApiV1AdminUsersUserIdRolesPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: RoleAssignment;
    userId: string;
};

export type AssignRolesApiV1AdminUsersUserIdRolesPatchResponse = (UserRead);

export type UpdateUserApiV1AdminUsersUserIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: AdminUserUpdate;
    userId: string;
};

export type UpdateUserApiV1AdminUsersUserIdPatchResponse = (UserRead);

export type DeleteUserApiV1AdminUsersUserIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    userId: string;
};

export type DeleteUserApiV1AdminUsersUserIdDeleteResponse = (app__schemas__Message);

export type ListRolesApiV1AdminRolesGetData = {
    accessToken?: (string | null);
};

export type ListRolesApiV1AdminRolesGetResponse = (Array<RoleRead>);

export type ListItemsApiV1ItemsGetData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListItemsApiV1ItemsGetResponse = (ItemList);

export type CreateItemApiV1ItemsPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: ItemCreate;
};

export type CreateItemApiV1ItemsPostResponse = (ItemRead);

export type ReadItemApiV1ItemsItemIdGetData = {
    accessToken?: (string | null);
    itemId: string;
};

export type ReadItemApiV1ItemsItemIdGetResponse = (ItemRead);

export type UpdateItemApiV1ItemsItemIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    itemId: string;
    requestBody: ItemUpdate;
};

export type UpdateItemApiV1ItemsItemIdPatchResponse = (ItemRead);

export type DeleteItemApiV1ItemsItemIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    itemId: string;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse = (app__schemas__Message);

export type ReadPortfolioApiV1PortfolioGetResponse = (PortfolioContentResponse);

export type ListPostsApiV1PortfolioPostsGetResponse = (Array<PublishedPostSummary>);

export type ReadPostApiV1PortfolioPostsSlugGetData = {
    slug: string;
};

export type ReadPostApiV1PortfolioPostsSlugGetResponse = (PublishedPostDetail);

export type ReadProjectApiV1PortfolioProjectsSlugGetData = {
    slug: string;
};

export type ReadProjectApiV1PortfolioProjectsSlugGetResponse = (PublishedProjectDetail);

export type ReadMediaApiV1PortfolioMediaMediaIdGetData = {
    mediaId: string;
};

export type ReadMediaApiV1PortfolioMediaMediaIdGetResponse = (unknown);

export type SubmitContactApiV1PortfolioContactPostData = {
    requestBody: ContactCreate;
};

export type SubmitContactApiV1PortfolioContactPostResponse = (ContactAccepted);

export type ReadSiteApiV1AdminPortfolioSiteGetData = {
    accessToken?: (string | null);
};

export type ReadSiteApiV1AdminPortfolioSiteGetResponse = (PortfolioSiteRead);

export type UpdateSiteApiV1AdminPortfolioSitePatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: PortfolioSiteUpdate;
};

export type UpdateSiteApiV1AdminPortfolioSitePatchResponse = (PortfolioSiteRead);

export type ListSectionsApiV1AdminPortfolioSectionsGetData = {
    accessToken?: (string | null);
};

export type ListSectionsApiV1AdminPortfolioSectionsGetResponse = (Array<SectionSettingRead>);

export type ReadSectionApiV1AdminPortfolioSectionsKeyGetData = {
    accessToken?: (string | null);
    key: string;
};

export type ReadSectionApiV1AdminPortfolioSectionsKeyGetResponse = (SectionSettingRead);

export type UpdateSectionApiV1AdminPortfolioSectionsKeyPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    key: string;
    requestBody: SectionSettingUpdate;
};

export type UpdateSectionApiV1AdminPortfolioSectionsKeyPatchResponse = (SectionSettingRead);

export type ListExpertiseApiV1AdminPortfolioExpertiseGetData = {
    accessToken?: (string | null);
};

export type ListExpertiseApiV1AdminPortfolioExpertiseGetResponse = (Array<HeroExpertiseRead>);

export type CreateExpertiseApiV1AdminPortfolioExpertisePostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: HeroExpertiseCreate;
};

export type CreateExpertiseApiV1AdminPortfolioExpertisePostResponse = (HeroExpertiseRead);

export type OrderExpertiseApiV1AdminPortfolioExpertiseOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderExpertiseApiV1AdminPortfolioExpertiseOrderPutResponse = (Array<HeroExpertiseRead>);

export type ReadExpertiseApiV1AdminPortfolioExpertiseRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadExpertiseApiV1AdminPortfolioExpertiseRecordIdGetResponse = (HeroExpertiseRead);

export type UpdateExpertiseApiV1AdminPortfolioExpertiseRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: HeroExpertiseUpdate;
};

export type UpdateExpertiseApiV1AdminPortfolioExpertiseRecordIdPatchResponse = (HeroExpertiseRead);

export type ArchiveExpertiseApiV1AdminPortfolioExpertiseRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchiveExpertiseApiV1AdminPortfolioExpertiseRecordIdDeleteResponse = (HeroExpertiseRead);

export type ListSocialLinksApiV1AdminPortfolioSocialLinksGetData = {
    accessToken?: (string | null);
};

export type ListSocialLinksApiV1AdminPortfolioSocialLinksGetResponse = (Array<SocialLinkRead>);

export type CreateSocialLinkApiV1AdminPortfolioSocialLinksPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: SocialLinkCreate;
};

export type CreateSocialLinkApiV1AdminPortfolioSocialLinksPostResponse = (SocialLinkRead);

export type OrderSocialLinksApiV1AdminPortfolioSocialLinksOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderSocialLinksApiV1AdminPortfolioSocialLinksOrderPutResponse = (Array<SocialLinkRead>);

export type ReadSocialLinkApiV1AdminPortfolioSocialLinksRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadSocialLinkApiV1AdminPortfolioSocialLinksRecordIdGetResponse = (SocialLinkRead);

export type UpdateSocialLinkApiV1AdminPortfolioSocialLinksRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: SocialLinkUpdate;
};

export type UpdateSocialLinkApiV1AdminPortfolioSocialLinksRecordIdPatchResponse = (SocialLinkRead);

export type ArchiveSocialLinkApiV1AdminPortfolioSocialLinksRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchiveSocialLinkApiV1AdminPortfolioSocialLinksRecordIdDeleteResponse = (SocialLinkRead);

export type ListAboutCardsApiV1AdminPortfolioAboutCardsGetData = {
    accessToken?: (string | null);
};

export type ListAboutCardsApiV1AdminPortfolioAboutCardsGetResponse = (Array<AboutCardRead>);

export type CreateAboutCardApiV1AdminPortfolioAboutCardsPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: AboutCardCreate;
};

export type CreateAboutCardApiV1AdminPortfolioAboutCardsPostResponse = (AboutCardRead);

export type OrderAboutCardsApiV1AdminPortfolioAboutCardsOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderAboutCardsApiV1AdminPortfolioAboutCardsOrderPutResponse = (Array<AboutCardRead>);

export type ReadAboutCardApiV1AdminPortfolioAboutCardsRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadAboutCardApiV1AdminPortfolioAboutCardsRecordIdGetResponse = (AboutCardRead);

export type UpdateAboutCardApiV1AdminPortfolioAboutCardsRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: AboutCardUpdate;
};

export type UpdateAboutCardApiV1AdminPortfolioAboutCardsRecordIdPatchResponse = (AboutCardRead);

export type ArchiveAboutCardApiV1AdminPortfolioAboutCardsRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchiveAboutCardApiV1AdminPortfolioAboutCardsRecordIdDeleteResponse = (AboutCardRead);

export type ListStacksApiV1AdminPortfolioStacksGetData = {
    accessToken?: (string | null);
};

export type ListStacksApiV1AdminPortfolioStacksGetResponse = (Array<TechnologyStackRead>);

export type CreateStackApiV1AdminPortfolioStacksPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: TechnologyStackCreate;
};

export type CreateStackApiV1AdminPortfolioStacksPostResponse = (TechnologyStackRead);

export type OrderStacksApiV1AdminPortfolioStacksOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderStacksApiV1AdminPortfolioStacksOrderPutResponse = (Array<TechnologyStackRead>);

export type ReadStackApiV1AdminPortfolioStacksRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadStackApiV1AdminPortfolioStacksRecordIdGetResponse = (TechnologyStackRead);

export type UpdateStackApiV1AdminPortfolioStacksRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: TechnologyStackUpdate;
};

export type UpdateStackApiV1AdminPortfolioStacksRecordIdPatchResponse = (TechnologyStackRead);

export type ArchiveStackApiV1AdminPortfolioStacksRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchiveStackApiV1AdminPortfolioStacksRecordIdDeleteResponse = (TechnologyStackRead);

export type ListServicesApiV1AdminPortfolioServicesGetData = {
    accessToken?: (string | null);
};

export type ListServicesApiV1AdminPortfolioServicesGetResponse = (Array<PortfolioServiceRead>);

export type CreateServiceApiV1AdminPortfolioServicesPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: PortfolioServiceCreate;
};

export type CreateServiceApiV1AdminPortfolioServicesPostResponse = (PortfolioServiceRead);

export type OrderServicesApiV1AdminPortfolioServicesOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderServicesApiV1AdminPortfolioServicesOrderPutResponse = (Array<PortfolioServiceRead>);

export type ReadServiceApiV1AdminPortfolioServicesRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadServiceApiV1AdminPortfolioServicesRecordIdGetResponse = (PortfolioServiceRead);

export type UpdateServiceApiV1AdminPortfolioServicesRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: PortfolioServiceUpdate;
};

export type UpdateServiceApiV1AdminPortfolioServicesRecordIdPatchResponse = (PortfolioServiceRead);

export type ArchiveServiceApiV1AdminPortfolioServicesRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchiveServiceApiV1AdminPortfolioServicesRecordIdDeleteResponse = (PortfolioServiceRead);

export type ListProjectsApiV1AdminPortfolioProjectsGetData = {
    accessToken?: (string | null);
};

export type ListProjectsApiV1AdminPortfolioProjectsGetResponse = (Array<PortfolioProjectRead>);

export type CreateProjectApiV1AdminPortfolioProjectsPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: PortfolioProjectCreate;
};

export type CreateProjectApiV1AdminPortfolioProjectsPostResponse = (PortfolioProjectRead);

export type OrderProjectsApiV1AdminPortfolioProjectsOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderProjectsApiV1AdminPortfolioProjectsOrderPutResponse = (Array<PortfolioProjectRead>);

export type ReadProjectApiV1AdminPortfolioProjectsRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadProjectApiV1AdminPortfolioProjectsRecordIdGetResponse = (PortfolioProjectRead);

export type UpdateProjectApiV1AdminPortfolioProjectsRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: PortfolioProjectUpdate;
};

export type UpdateProjectApiV1AdminPortfolioProjectsRecordIdPatchResponse = (PortfolioProjectRead);

export type ArchiveProjectApiV1AdminPortfolioProjectsRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchiveProjectApiV1AdminPortfolioProjectsRecordIdDeleteResponse = (PortfolioProjectRead);

export type ListCategoriesApiV1AdminPortfolioCategoriesGetData = {
    accessToken?: (string | null);
};

export type ListCategoriesApiV1AdminPortfolioCategoriesGetResponse = (Array<PostCategoryRead>);

export type CreateCategoryApiV1AdminPortfolioCategoriesPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: PostCategoryCreate;
};

export type CreateCategoryApiV1AdminPortfolioCategoriesPostResponse = (PostCategoryRead);

export type OrderCategoriesApiV1AdminPortfolioCategoriesOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderCategoriesApiV1AdminPortfolioCategoriesOrderPutResponse = (Array<PostCategoryRead>);

export type ReadCategoryApiV1AdminPortfolioCategoriesRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadCategoryApiV1AdminPortfolioCategoriesRecordIdGetResponse = (PostCategoryRead);

export type UpdateCategoryApiV1AdminPortfolioCategoriesRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: PostCategoryUpdate;
};

export type UpdateCategoryApiV1AdminPortfolioCategoriesRecordIdPatchResponse = (PostCategoryRead);

export type ArchiveCategoryApiV1AdminPortfolioCategoriesRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchiveCategoryApiV1AdminPortfolioCategoriesRecordIdDeleteResponse = (PostCategoryRead);

export type ListPostsApiV1AdminPortfolioPostsGetData = {
    accessToken?: (string | null);
};

export type ListPostsApiV1AdminPortfolioPostsGetResponse = (Array<PortfolioPostRead>);

export type CreatePostApiV1AdminPortfolioPostsPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: PortfolioPostCreate;
};

export type CreatePostApiV1AdminPortfolioPostsPostResponse = (PortfolioPostRead);

export type OrderPostsApiV1AdminPortfolioPostsOrderPutData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: CollectionOrderUpdate;
};

export type OrderPostsApiV1AdminPortfolioPostsOrderPutResponse = (Array<PortfolioPostRead>);

export type ReadPostApiV1AdminPortfolioPostsRecordIdGetData = {
    accessToken?: (string | null);
    recordId: string;
};

export type ReadPostApiV1AdminPortfolioPostsRecordIdGetResponse = (PortfolioPostRead);

export type UpdatePostApiV1AdminPortfolioPostsRecordIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
    requestBody: PortfolioPostUpdate;
};

export type UpdatePostApiV1AdminPortfolioPostsRecordIdPatchResponse = (PortfolioPostRead);

export type ArchivePostApiV1AdminPortfolioPostsRecordIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    recordId: string;
};

export type ArchivePostApiV1AdminPortfolioPostsRecordIdDeleteResponse = (PortfolioPostRead);

export type ListMediaApiV1AdminPortfolioMediaGetData = {
    accessToken?: (string | null);
    includeArchived?: boolean;
};

export type ListMediaApiV1AdminPortfolioMediaGetResponse = (Array<MediaAssetRead>);

export type UploadMediaApiV1AdminPortfolioMediaPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    formData: Body_upload_media_api_v1_admin_portfolio_media_post;
};

export type UploadMediaApiV1AdminPortfolioMediaPostResponse = (MediaAssetRead);

export type UpdateMediaApiV1AdminPortfolioMediaMediaIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    mediaId: string;
    requestBody: MediaAssetUpdate;
};

export type UpdateMediaApiV1AdminPortfolioMediaMediaIdPatchResponse = (MediaAssetRead);

export type DeleteMediaApiV1AdminPortfolioMediaMediaIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    mediaId: string;
    purge?: boolean;
};

export type DeleteMediaApiV1AdminPortfolioMediaMediaIdDeleteResponse = (app__portfolio__schemas__Message);

export type PreviewApiV1AdminPortfolioPreviewGetData = {
    accessToken?: (string | null);
};

export type PreviewApiV1AdminPortfolioPreviewGetResponse = (PortfolioContentResponse);

export type PublishApiV1AdminPortfolioPublishPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
};

export type PublishApiV1AdminPortfolioPublishPostResponse = (PortfolioPublicationRead);

export type ListPublicationsApiV1AdminPortfolioPublicationsGetData = {
    accessToken?: (string | null);
};

export type ListPublicationsApiV1AdminPortfolioPublicationsGetResponse = (Array<PortfolioPublicationRead>);

export type RestorePublicationApiV1AdminPortfolioPublicationsPublicationIdRestorePostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    publicationId: string;
};

export type RestorePublicationApiV1AdminPortfolioPublicationsPublicationIdRestorePostResponse = (PortfolioPublicationRead);

export type ListContactsApiV1AdminPortfolioContactsGetData = {
    accessToken?: (string | null);
    includeArchived?: boolean;
};

export type ListContactsApiV1AdminPortfolioContactsGetResponse = (Array<ContactSubmissionRead>);

export type UpdateContactApiV1AdminPortfolioContactsSubmissionIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: ContactSubmissionUpdate;
    submissionId: string;
};

export type UpdateContactApiV1AdminPortfolioContactsSubmissionIdPatchResponse = (ContactSubmissionRead);

export type RetryContactEmailApiV1AdminPortfolioContactsSubmissionIdRetryEmailPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    submissionId: string;
};

export type RetryContactEmailApiV1AdminPortfolioContactsSubmissionIdRetryEmailPostResponse = (ContactSubmissionRead);