// This file is auto-generated by @hey-api/openapi-ts

/**
 * Payload for creating a user from the admin interface.
 */
export type AdminUserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    role_names?: Array<(string)>;
};

/**
 * Payload for admin-managed user updates.
 */
export type AdminUserUpdate = {
    email?: (string | null);
    full_name?: (string | null);
    password?: (string | null);
    is_active?: (boolean | null);
    role_names?: (Array<(string)> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Payload for creating an item.
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Paginated item list response.
 */
export type ItemList = {
    data: Array<ItemRead>;
    count: number;
};

/**
 * Item data returned by item endpoints.
 */
export type ItemRead = {
    id: string;
    title: string;
    description?: (string | null);
    owner_id: string;
};

/**
 * Payload for updating an item.
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Email and password login payload.
 */
export type LoginRequest = {
    email: string;
    password: string;
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Payload for changing the current user's password.
 */
export type PasswordChange = {
    current_password: string;
    new_password: string;
};

/**
 * Payload for requesting a password recovery email.
 */
export type PasswordRecoveryRequest = {
    email: string;
};

/**
 * Payload for completing password reset with a token.
 */
export type PasswordResetRequest = {
    token: string;
    new_password: string;
};

/**
 * Permission data exposed to the frontend.
 */
export type PermissionRead = {
    code: string;
    description: string;
};

/**
 * Payload for updating the current user's profile.
 */
export type ProfileUpdate = {
    full_name?: (string | null);
    email?: (string | null);
};

/**
 * Payload for assigning roles to a user.
 */
export type RoleAssignment = {
    role_names: Array<(string)>;
};

/**
 * Role data with attached permissions.
 */
export type RoleRead = {
    id: string;
    name: string;
    description: string;
    permissions?: Array<PermissionRead>;
};

/**
 * Payload for creating a self-service user account.
 */
export type UserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Paginated user list response.
 */
export type UserList = {
    data: Array<UserRead>;
    count: number;
};

/**
 * Public user data returned by account and admin endpoints.
 */
export type UserRead = {
    id: string;
    email: string;
    full_name?: (string | null);
    is_active: boolean;
    roles?: Array<RoleRead>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthApiV1HealthGetResponse = ({
    [key: string]: (string);
});

export type StatusApiV1HealthStatusGetResponse = ({
    [key: string]: unknown;
});

export type LoginApiV1AuthLoginPostData = {
    requestBody: LoginRequest;
};

export type LoginApiV1AuthLoginPostResponse = (UserRead);

export type SignupApiV1AuthSignupPostData = {
    requestBody: UserCreate;
};

export type SignupApiV1AuthSignupPostResponse = (UserRead);

export type RefreshApiV1AuthRefreshPostData = {
    refreshToken?: (string | null);
};

export type RefreshApiV1AuthRefreshPostResponse = (UserRead);

export type LogoutApiV1AuthLogoutPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
};

export type LogoutApiV1AuthLogoutPostResponse = ({
    [key: string]: (string);
});

export type MeApiV1AuthMeGetData = {
    accessToken?: (string | null);
};

export type MeApiV1AuthMeGetResponse = (UserRead);

export type UpdateMeApiV1AuthMePatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: ProfileUpdate;
};

export type UpdateMeApiV1AuthMePatchResponse = (UserRead);

export type DeleteMeApiV1AuthMeDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
};

export type DeleteMeApiV1AuthMeDeleteResponse = (Message);

export type ChangePasswordApiV1AuthMePasswordPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: PasswordChange;
};

export type ChangePasswordApiV1AuthMePasswordPostResponse = ({
    [key: string]: (string);
});

export type RecoverPasswordApiV1AuthPasswordRecoveryPostData = {
    requestBody: PasswordRecoveryRequest;
};

export type RecoverPasswordApiV1AuthPasswordRecoveryPostResponse = (Message);

export type ResetPasswordApiV1AuthResetPasswordPostData = {
    requestBody: PasswordResetRequest;
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse = (Message);

export type ListUsersApiV1AdminUsersGetData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListUsersApiV1AdminUsersGetResponse = (UserList);

export type CreateUserApiV1AdminUsersPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: AdminUserCreate;
};

export type CreateUserApiV1AdminUsersPostResponse = (UserRead);

export type AssignRolesApiV1AdminUsersUserIdRolesPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: RoleAssignment;
    userId: string;
};

export type AssignRolesApiV1AdminUsersUserIdRolesPatchResponse = (UserRead);

export type UpdateUserApiV1AdminUsersUserIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: AdminUserUpdate;
    userId: string;
};

export type UpdateUserApiV1AdminUsersUserIdPatchResponse = (UserRead);

export type DeleteUserApiV1AdminUsersUserIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    userId: string;
};

export type DeleteUserApiV1AdminUsersUserIdDeleteResponse = (Message);

export type ListRolesApiV1AdminRolesGetData = {
    accessToken?: (string | null);
};

export type ListRolesApiV1AdminRolesGetResponse = (Array<RoleRead>);

export type ListItemsApiV1ItemsGetData = {
    accessToken?: (string | null);
    limit?: number;
    skip?: number;
};

export type ListItemsApiV1ItemsGetResponse = (ItemList);

export type CreateItemApiV1ItemsPostData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    requestBody: ItemCreate;
};

export type CreateItemApiV1ItemsPostResponse = (ItemRead);

export type ReadItemApiV1ItemsItemIdGetData = {
    accessToken?: (string | null);
    itemId: string;
};

export type ReadItemApiV1ItemsItemIdGetResponse = (ItemRead);

export type UpdateItemApiV1ItemsItemIdPatchData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    itemId: string;
    requestBody: ItemUpdate;
};

export type UpdateItemApiV1ItemsItemIdPatchResponse = (ItemRead);

export type DeleteItemApiV1ItemsItemIdDeleteData = {
    accessToken?: (string | null);
    csrfToken?: (string | null);
    itemId: string;
};

export type DeleteItemApiV1ItemsItemIdDeleteResponse = (Message);