"""portfolio cms foundation

Revision ID: 8d6b927b3d83
Revises: 202606230001
Create Date: 2026-07-13 11:26:06.992662
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "8d6b927b3d83"
down_revision: str | None = "202606230001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_submission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("inbox_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("delivery_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_error", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_submission_delivery_state"),
        "contact_submission",
        ["delivery_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_submission_email"), "contact_submission", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_contact_submission_inbox_state"),
        "contact_submission",
        ["inbox_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_submission_is_archived"),
        "contact_submission",
        ["is_archived"],
        unique=False,
    )
    op.create_table(
        "hero_expertise",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hero_expertise_is_archived"), "hero_expertise", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_hero_expertise_sort_order"), "hero_expertise", ["sort_order"], unique=False
    )
    op.create_table(
        "portfolio_section_setting",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("heading", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("navigation_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "portfolio_service",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("icon_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_service_is_archived"), "portfolio_service", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_service_sort_order"), "portfolio_service", ["sort_order"], unique=False
    )
    op.create_table(
        "post_category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_category_is_archived"), "post_category", ["is_archived"], unique=False
    )
    op.create_index(op.f("ix_post_category_name"), "post_category", ["name"], unique=True)
    op.create_index(op.f("ix_post_category_slug"), "post_category", ["slug"], unique=True)
    op.create_index(
        op.f("ix_post_category_sort_order"), "post_category", ["sort_order"], unique=False
    )
    op.create_table(
        "social_link",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_social_link_is_archived"), "social_link", ["is_archived"], unique=False
    )
    op.create_index(op.f("ix_social_link_sort_order"), "social_link", ["sort_order"], unique=False)
    op.create_table(
        "technology_stack",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("code_snippet", sa.Text(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("use_cases", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_technology_stack_is_archived"), "technology_stack", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_technology_stack_language"), "technology_stack", ["language"], unique=True
    )
    op.create_index(
        op.f("ix_technology_stack_sort_order"), "technology_stack", ["sort_order"], unique=False
    )
    op.create_table(
        "media_asset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alt_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("storage_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("byte_data", sa.LargeBinary(), nullable=True),
        sa.Column("static_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("local_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_asset_checksum"), "media_asset", ["checksum"], unique=False)
    op.create_index(
        op.f("ix_media_asset_is_archived"), "media_asset", ["is_archived"], unique=False
    )
    op.create_table(
        "portfolio_publication",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("published_by_id", sa.Uuid(), nullable=False),
        sa.Column("restored_from_id", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["published_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restored_from_id"], ["portfolio_publication.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_publication_checksum"),
        "portfolio_publication",
        ["checksum"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_publication_published_at"),
        "portfolio_publication",
        ["published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_publication_version"), "portfolio_publication", ["version"], unique=True
    )
    op.create_table(
        "about_card",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("media_id", sa.Uuid(), nullable=True),
        sa.Column("image_alt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("layout", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_fit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_ratio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["media_id"], ["media_asset.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_about_card_is_archived"), "about_card", ["is_archived"], unique=False)
    op.create_index(op.f("ix_about_card_sort_order"), "about_card", ["sort_order"], unique=False)
    op.create_table(
        "portfolio_post",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("cover_media_id", sa.Uuid(), nullable=True),
        sa.Column("published_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seo_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("seo_description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["post_category.id"],
        ),
        sa.ForeignKeyConstraint(["cover_media_id"], ["media_asset.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_post_category_id"), "portfolio_post", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_post_is_archived"), "portfolio_post", ["is_archived"], unique=False
    )
    op.create_index(op.f("ix_portfolio_post_slug"), "portfolio_post", ["slug"], unique=True)
    op.create_index(
        op.f("ix_portfolio_post_sort_order"), "portfolio_post", ["sort_order"], unique=False
    )
    op.create_table(
        "portfolio_project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("case_study_markdown", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("media_id", sa.Uuid(), nullable=True),
        sa.Column("external_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("live_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("repository_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("seo_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("seo_description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media_asset.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_project_is_archived"), "portfolio_project", ["is_archived"], unique=False
    )
    op.create_index(op.f("ix_portfolio_project_slug"), "portfolio_project", ["slug"], unique=True)
    op.create_index(
        op.f("ix_portfolio_project_sort_order"), "portfolio_project", ["sort_order"], unique=False
    )
    op.create_table(
        "portfolio_site",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("public_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notification_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hero_summary", sa.Text(), nullable=False),
        sa.Column("hero_primary_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hero_primary_href", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hero_secondary_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hero_secondary_href", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hero_portrait_media_id", sa.Uuid(), nullable=True),
        sa.Column("profile_media_id", sa.Uuid(), nullable=True),
        sa.Column("about_note_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("about_note_summary", sa.Text(), nullable=False),
        sa.Column("consultation_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("consultation_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("consultation_media_id", sa.Uuid(), nullable=True),
        sa.Column("footer_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("seo_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("seo_description", sa.Text(), nullable=False),
        sa.Column("seo_image_media_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["consultation_media_id"], ["media_asset.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["hero_portrait_media_id"], ["media_asset.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["profile_media_id"], ["media_asset.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seo_image_media_id"], ["media_asset.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "portfolio_state",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_publication_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_publication_id"], ["portfolio_publication.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_state")
    op.drop_table("portfolio_site")
    op.drop_index(op.f("ix_portfolio_project_sort_order"), table_name="portfolio_project")
    op.drop_index(op.f("ix_portfolio_project_slug"), table_name="portfolio_project")
    op.drop_index(op.f("ix_portfolio_project_is_archived"), table_name="portfolio_project")
    op.drop_table("portfolio_project")
    op.drop_index(op.f("ix_portfolio_post_sort_order"), table_name="portfolio_post")
    op.drop_index(op.f("ix_portfolio_post_slug"), table_name="portfolio_post")
    op.drop_index(op.f("ix_portfolio_post_is_archived"), table_name="portfolio_post")
    op.drop_index(op.f("ix_portfolio_post_category_id"), table_name="portfolio_post")
    op.drop_table("portfolio_post")
    op.drop_index(op.f("ix_about_card_sort_order"), table_name="about_card")
    op.drop_index(op.f("ix_about_card_is_archived"), table_name="about_card")
    op.drop_table("about_card")
    op.drop_index(op.f("ix_portfolio_publication_version"), table_name="portfolio_publication")
    op.drop_index(op.f("ix_portfolio_publication_published_at"), table_name="portfolio_publication")
    op.drop_index(op.f("ix_portfolio_publication_checksum"), table_name="portfolio_publication")
    op.drop_table("portfolio_publication")
    op.drop_index(op.f("ix_media_asset_is_archived"), table_name="media_asset")
    op.drop_index(op.f("ix_media_asset_checksum"), table_name="media_asset")
    op.drop_table("media_asset")
    op.drop_index(op.f("ix_technology_stack_sort_order"), table_name="technology_stack")
    op.drop_index(op.f("ix_technology_stack_language"), table_name="technology_stack")
    op.drop_index(op.f("ix_technology_stack_is_archived"), table_name="technology_stack")
    op.drop_table("technology_stack")
    op.drop_index(op.f("ix_social_link_sort_order"), table_name="social_link")
    op.drop_index(op.f("ix_social_link_is_archived"), table_name="social_link")
    op.drop_table("social_link")
    op.drop_index(op.f("ix_post_category_sort_order"), table_name="post_category")
    op.drop_index(op.f("ix_post_category_slug"), table_name="post_category")
    op.drop_index(op.f("ix_post_category_name"), table_name="post_category")
    op.drop_index(op.f("ix_post_category_is_archived"), table_name="post_category")
    op.drop_table("post_category")
    op.drop_index(op.f("ix_portfolio_service_sort_order"), table_name="portfolio_service")
    op.drop_index(op.f("ix_portfolio_service_is_archived"), table_name="portfolio_service")
    op.drop_table("portfolio_service")
    op.drop_table("portfolio_section_setting")
    op.drop_index(op.f("ix_hero_expertise_sort_order"), table_name="hero_expertise")
    op.drop_index(op.f("ix_hero_expertise_is_archived"), table_name="hero_expertise")
    op.drop_table("hero_expertise")
    op.drop_index(op.f("ix_contact_submission_is_archived"), table_name="contact_submission")
    op.drop_index(op.f("ix_contact_submission_inbox_state"), table_name="contact_submission")
    op.drop_index(op.f("ix_contact_submission_email"), table_name="contact_submission")
    op.drop_index(op.f("ix_contact_submission_delivery_state"), table_name="contact_submission")
    op.drop_table("contact_submission")
    # ### end Alembic commands ###
